title: Yubika Bhattarai # your name (or website title) here
logo: "/images/1596681234552.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Project Portfolio
  <br><br>
  More projects coming soon!!
  <br><br>
  <a href="https://www.linkedin.com/in/yubika-bhattarai-106112a2/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
